version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online_shopping
    ports:
      - "8080:8098"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://host.docker.internal:5432/postgres
#      jdbc:postgresql://localhost:5433/postgres
       #jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: AAaa123456,./
    networks:
      - your-network

  db:
    image: postgres
    container_name: my_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AAaa123456,./
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - your-network

networks:
  your-network:
    driver: bridge