name: Deploy to EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Upload JAR file via SFTP
        run: |
          lftp -u ${{ secrets.EC2_USER }},${{ secrets.EC2_SSH_KEY }} -e "
            put ./gatewayapp/build/libs/gatewayapp-0.0.1-SNAPSHOT.jar -o /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar
            bye
          " sftp://${{ secrets.EC2_HOST }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy and restart service on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Updating JAR file and restarting service..."
            # Stop the service
            sudo systemctl stop gatewayapp.service
            # Replace the old JAR with the new one
            sudo cp /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar
            # Reload and restart the service
            sudo systemctl daemon-reload
            sudo systemctl start gatewayapp.service
            # Check the status of the service
            sudo systemctl status gatewayapp.service