name: Deploy to EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SFTP and SSH tools
        run: sudo apt-get install -y openssh-client

      - name: Upload JAR file via SFTP
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          sftp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<EOF
            put ./gatewayapp/build/libs/gatewayapp-0.0.1-SNAPSHOT.jar /home/ubuntu/gatewayapp-0.0.1-SNAPSHOT.jar
            bye
          EOF

      - name: Restart service on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Updating JAR file and restarting service..."
            # Stop the service
            sudo systemctl stop gatewayapp.service
            # Reload the systemd configuration
            sudo systemctl daemon-reload
            # Start the service
            sudo systemctl start gatewayapp.service
            # Check the status of the service test
            sudo systemctl status gatewayapp.service