name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build online-shopping with Gradle
        run: gradle build -x test bootJar
        shell: sh
        working-directory: ./gatewayapp
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      # Проверим, что статические файлы существуют после сборки
      - name: List static resources
        run: ls -R gatewayapp/build/resources/static
        shell: sh

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-jar
          path: gatewayapp/build/libs/*.jar

      - name: Archive Static Resources
        uses: actions/upload-artifact@v2
        with:
          name: static-resources
          path: gatewayapp/build/resources/static

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt

      # Скачиваем артефакты перед тестами
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-jar
          path: gatewayapp/build/libs/

      - name: Download static resources
        uses: actions/download-artifact@v2
        with:
          name: static-resources
          path: gatewayapp/build/resources/static

      - name: Build with Gradle Wrapper
        shell: sh
        run: gradle test
        working-directory: ./gatewayapp

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull build artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-jar
          path: build/libs/

      - name: Download static resources
        uses: actions/download-artifact@v2
        with:
          name: static-resources
          path: gatewayapp/build/resources/static

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build and push Docker image
        run: |
          docker build -t spring-security-app:latest .
          docker push huseyn047/spring-security-app