name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main"

      jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: amazon

      - name: Build online-shopping app with Gradle
        run: gradle build -x test bootJar -Dorg.gradle.jvmargs="-Xmx4096m"
        working-directory: ./spring-security/gatewayapp

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-jar
          path: spring-security/gatewayapp/build/libs/*.jar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: amazon

      - name: Initialize Gradle build
        run: gradle init

      - name: Run tests with Gradle
        run: gradle test
        working-directory: ./spring-security/gatewayapp

  docker-build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull build artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-jar
          path: spring-security/gatewayapp/build/libs/

      - name: Build and push Docker image
        run: |
          docker build -t huseyn047/online-shopping-app:latest spring-security/gatewayapp
          docker push huseyn047/online-shopping-app:latest