name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'amazon'

      - name: Build with Gradle
        run: gradle build -x test bootJar -Dorg.gradle.jvmargs="-Xmx4096m"
        working-directory: ./your-project-directory

      - name: Run tests
        run: gradle test
        working-directory: ./your-project-directory

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: your-docker-repo/your-image-name
          tag_with_ref: true